"""
[FEAT-485] Unit Tests for Archive Node Temporal Scarcity Diagnostic Envelope

Tests the epistemological evidence envelope generated by ArchiveNode.get_context()
when year filtering yields zero matches in the queried year but matches exist across
other eras in the 18-year archive.
"""

import asyncio
import json
import sys
from unittest.mock import patch, MagicMock

# Mock third-party dependencies if missing in runner environment
for mod in ['chromadb', 'aiohttp', 'mcp', 'mcp.server', 'mcp.server.fastmcp', 'fastmcp', 'fastembed']:
    if mod not in sys.modules:
        sys.modules[mod] = MagicMock()

if 'nodes.loader' not in sys.modules:
    mock_loader = MagicMock()
    # Ensure @mcp.tool() acts as a passthrough decorator
    mock_loader.BicameralNode.return_value.mcp.tool = lambda *args, **kwargs: (lambda fn: fn)
    sys.modules['nodes.loader'] = mock_loader
    sys.modules['loader'] = mock_loader

import pytest


class TestArchiveNodeScarcity:
    """Test suite for Archive Node temporal scarcity & epistemological envelope."""

    def test_scarcity_envelope_with_out_of_era_matches(self):
        """When an entity matches in 2014 but query targets 2008, return temporal diagnostic."""
        from src.nodes.archive_node import get_context

        mock_fused = [
            (
                'doc_2014_1',
                {
                    'date': '2014-06-15',
                    'timestamp': '2014_06',
                    'source': '2014_06.json',
                    'text_anchor': 'Kayak PCIe telemetry validation framework deployment',
                    'summary': 'Kayak PCIe telemetry validation framework',
                    '_rrf_score': 0.95
                }
            )
        ]

        with patch('src.nodes.archive_node.embed_texts', return_value=[[0.1] * 384]), \
             patch('src.nodes.archive_node.wisdom.query', return_value={'documents': [[]], 'metadatas': [[]]}), \
             patch('src.nodes.archive_node.stream.query', return_value={'documents': [[]], 'metadatas': [[]]}), \
             patch('src.nodes.archive_node.keyword_search', return_value=[]), \
             patch('src.nodes.archive_node.rrf_fuse', return_value=mock_fused), \
             patch('src.nodes.archive_node.get_observational_memo', return_value=''), \
             patch('os.path.exists', side_effect=lambda p: False if '2008.json' in p or '2007.json' in p else True):

            res_raw = asyncio.run(get_context(query='was Kayak really in 2008?', domain='lab_history'))
            res = json.loads(res_raw)

            assert res.get('found') is True
            context = res.get('context', '')
            assert '[ARCHIVAL_EVIDENCE]' in context
            assert 'Target Year Evaluated: 2008' in context
            assert '2014' in context
            assert 'ABSENT in target year 2008' in context

    def test_scarcity_envelope_when_no_records_exist_anywhere(self):
        """When an entity has zero matches across all eras, return universal scarcity diagnostic."""
        from src.nodes.archive_node import get_context

        with patch('src.nodes.archive_node.embed_texts', return_value=[[0.1] * 384]), \
             patch('src.nodes.archive_node.wisdom.query', return_value={'documents': [[]], 'metadatas': [[]]}), \
             patch('src.nodes.archive_node.stream.query', return_value={'documents': [[]], 'metadatas': [[]]}), \
             patch('src.nodes.archive_node.keyword_search', return_value=[]), \
             patch('src.nodes.archive_node.rrf_fuse', return_value=[]), \
             patch('src.nodes.archive_node.get_observational_memo', return_value=''):

            res_raw = asyncio.run(get_context(query='was NonExistentProject in 2019?', domain='lab_history'))
            res = json.loads(res_raw)

            assert res.get('found') is False
            assert 'No relevant historical notes found' in res.get('reason', '')
