[pytest]
testpaths = tests/ src/tests/
pythonpath = . src
asyncio_mode = auto
filterwarnings =
    ignore::FutureWarning:torch.cuda.*
    ignore::DeprecationWarning:torchao.*
    ignore::FutureWarning:torch.*