from nodes.loader import BicameralNode
import logging
import os
import json
import glob
import datetime

LAB_SYSTEM_PROMPT = (
    "You are The Lab Node, the Sentient Sentinel and Situational Auditor of the Acme Lab. "
    "CORE ROLE: You overheard all bicameral interactions. You provide dynamic VIBES and coordination HINTS. "
    "TASK: For every query, you MUST provide a high-fidelity scalar triage in JSON format. "
    "FORMAT: Return ONLY a JSON object with this schema: "
    "{"
    "  \"intent\": \"CASUAL | STRATEGIC | TACTICAL | OPERATIONAL\", "
    "  \"topic\": \"Historical | Silicon | Code | Meta | Math | Speculative | Casual\", "
    "  \"domain\": \"exp_tlm | exp_bkm | exp_for | standard\", "
    "  \"casual\": 0.0-1.0, \"intrigue\": 0.0-1.0, \"importance\": 0.0-1.0, "
    "  \"situation\": \"Short description\", \"hints\": \"Coordination guidance\""
    "} "
    "STEERAGE RULES: "
    "1. ACTION TAGS: If the query contains '[ACTION: UPLINK]', importance MUST be 1.0. "
    "2. DIRECTIONAL TRIAGE: Detect if the user is addressing 'Brain', 'Pinky', or 'Lab'. "
    "   - If 'Brain', importance MUST be >= 0.8. "
    "   - If 'Pinky', casual MUST be >= 0.8. "
    "3. If query relates to technical history or specific years, importance must be >= 0.6. "
    "4. If query involves MATH or complex derivation, importance must be >= 0.8. "
    "5. BKM STANDARDIZATION: Ensure all generated templates follow the Execution/Validation/Scars format."
)

node = BicameralNode("Lab", LAB_SYSTEM_PROMPT)
mcp = node.mcp

# Paths
FIELD_NOTES_DATA = os.path.expanduser("~/Dev_Lab/Portfolio_Dev/field_notes/data")
SEMANTIC_MAP_FILE = os.path.join(FIELD_NOTES_DATA, "semantic_map.json")

# NOTE: triage_situational_vibe and triage_response wrappers removed.
# Node now speaks natively via BicameralNode.run() sampling bridge.

@mcp.tool()
async def generate_bkm(topic: str, category: str = "validation") -> str:
    """The Blueprint Generator: Creates a high-density BKM template."""
    template = f"""# BKM: {topic.upper()}
**Category:** {category.capitalize()}
**Status:** DRAFT (Architect Node)

## 🏎️ 1. Execution (One-Liner)
`[Insert critical command here]`

## 🧪 2. Validation Logic
- [ ] Step 1: Verify [X]
- [ ] Step 2: Monitor [Y]

## 🤕 3. Scars (Known Failures)
- Failure A: [Describe] -> Mitigation: [Describe]

---
*Generated by The Architect*
"""
    return template


@mcp.tool()
async def build_semantic_map() -> str:
    """Refactors artifacts into a 3-layer hierarchy: Strategic, Analytical, Tactical."""
    logging.info("Architect is deepening the semantic map...")
    artifacts = glob.glob(os.path.join(FIELD_NOTES_DATA, "20*.json"))
    
    hierarchy = {
        "strategic_layer": [], # Rank 4 (Diamond) anchors - Career PIVOTS
        "analytical_layer": {}, # Theme-based insight clusters - TECHNICAL DOMAINS
        "tactical_layer": {
            "total_events": 0,
            "year_distribution": {},
            "description": "Raw chronological technical evidence."
        },
        "meta_layer": {
            "resonance_score": 0.0,
            "active_themes": [],
            "last_refactor": datetime.datetime.now().isoformat()
        }
    }
    
    theme_keywords = ["telemetry", "silicon", "validation", "automation", "agentic", "architecture"]

    for art_path in artifacts:
        year = os.path.basename(art_path).replace(".json", "")
        hierarchy["tactical_layer"]["year_distribution"][year] = 0
        
        try:
            with open(art_path, 'r') as f:
                data = json.load(f)
                if not isinstance(data, list):
                    continue
                
                hierarchy["tactical_layer"]["total_events"] += len(data)
                hierarchy["tactical_layer"]["year_distribution"][year] = len(data)
                
                for item in data:
                    rank = item.get('rank', 2)
                    summary = item.get('summary', '')
                    technical_gem = item.get('technical_gem', '')
                    
                    # Layer 1: Strategic (Diamond)
                    if rank >= 4:
                        hierarchy["strategic_layer"].append({
                            "year": year, 
                            "anchor": summary[:100],
                            "gem": technical_gem
                        })
                    
                    # Layer 2: Analytical (Themes)
                    for kw in theme_keywords:
                        summary_low = str(summary).lower() if summary else ""
                        gem_low = str(technical_gem).lower() if technical_gem else ""
                        
                        if kw in summary_low or kw in gem_low:
                            if kw not in hierarchy["analytical_layer"]:
                                hierarchy["analytical_layer"][kw] = []
                            # Store unique technical gems per theme
                            if technical_gem and str(technical_gem) not in [str(g.get('gem')) for g in hierarchy["analytical_layer"][kw]]:
                                hierarchy["analytical_layer"][kw].append({
                                    "year": year, 
                                    "gem": technical_gem,
                                    "summary": summary[:150] if summary else ""
                                })
        except Exception as e:
            logging.error(f"Error processing {art_path}: {e}")

    # Prune themes to top 15 high-fidelity entries
    for kw in hierarchy["analytical_layer"]:
        hierarchy["analytical_layer"][kw] = hierarchy["analytical_layer"][kw][:15]

    with open(SEMANTIC_MAP_FILE, 'w') as f:
        json.dump(hierarchy, f, indent=2)

    return f"Map Deepened. {len(hierarchy['strategic_layer'])} strategic anchors and {len(hierarchy['analytical_layer'])} analytical themes clustered."


@mcp.tool()
async def ping_engine(force: bool = False) -> str:
    """[FEAT-192] Verify and force engine readiness."""
    success, msg = await node.ping_engine(force=force)
    return json.dumps({"success": success, "message": msg})


if __name__ == "__main__":
    node.run() # [FEAT-240] Run the Native Sampling Bridge
